name: Build App

on:
  push:
    branches:
      - main  # назва головної гілки
    paths:
      - 'king.cs'

# додаємо глобальну змінну середовища для примусового використання Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_NODE_TYPE: node24

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained false -o ./output /p:PublishReadyToRun=true /p:OptimizationPreference=Size
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: bro-Gemini-Windows
        path: ./output
